[providers]
	[providers.mysql]
	backup_dir = "backups"
	backup_post_cmd = "rm -rf $volume/backups"
	detect_cmd = "[[ -d $volume/mysql ]]"
	backup_pre_cmd = """
	mkdir -p $volume/backups && \
	echo $(if [ -z '$MYSQL_ROOT_PASSWORD' ]; then \
	  mysqldump --all-databases --extended-insert --user=$MYSQL_USER --password=$MYSQL_PASSWORD; else \
	  mysqldump --all-databases --extended-insert --password=$MYSQL_ROOT_PASSWORD; \
	fi) > $volume/backups/all.sql"""

	[providers.postgresql]
	backup_dir = "backups"
	backup_post_cmd = "rm -rf $volume/backups"
	backup_pre_cmd = "mkdir -p $volume/backups && pg_dumpall --clean -Upostgres > $volume/backups/all.sql"
	detect_cmd = "[[ -f $volume/PG_VERSION ]]"

	[providers.openldap]
	backup_pre_cmd = "mkdir -p $volume/backups && slapcat > $volume/backups/all.ldif"
	detect_cmd = "[[ -f $volume/DB_CONFIG ]]"
	backup_dir = "backups"

	[providers.mongo]
	backup_dir = "backups"
	backup_post_cmd = "rm -rf $volume/backups"
	backup_pre_cmd = "mongodump -o $volume/backups"
	detect_cmd = "[[ -f $volume/mongod.lock ]]"
	restore_post_cmd = "mongorestore --dir $volume/backups && rm -rf $volume/backups"
