apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "volback.fullname" . }}
  labels:
    app: {{ template "volback.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  aws_access_key: {{ .Values.config.awsAccessKey | quote }}
  forget_args: {{ .Values.config.forgetArgs | quote }}
  refresh_time: {{ .Values.config.refreshTime | quote }}
  target_url: {{ .Values.config.targetUrl | quote }}
