mysql:
  backup-file: "backup.sql"
  data-location: "/var/lib/mysql"
  backup: "mysqldump --user=root --password=<MYSQL_ROOT_PASSWORD> --all-databases > %DUMP%"
  restore: "cat %DUMP% | mysql --user=root --password=<MYSQL_ROOT_PASSWORD>"
