image:
  repository: codejamninja/volback
  tag: 3.0.0
  pullPolicy: IfNotPresent

config:
  awsAccessKey: ''
  awsSecretKey: ''
  forgetArgs: '--keep-last 3'
  refreshTime: 10
  resticPassword: volback
  serverPsk: volback
  targetUrl: ''

volback:
  env: {}

service:
  type: NodePort
  externalTrafficPolicy: Cluster
  nodePorts:
    volback:
      http: ''

ingress:
  enabled: false
  tls: false
  hosts:
    volback:
      - name: ''
        path: /

issuer:
  name: letsencrypt-staging
  kind: ClusterIssuer

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1

serviceAccount:
  create: true
  name: ''
