'/user/': user_controller.UserInstance
'/users/': user_controller.UserList
'/auth/login/': auth_controller.Login
'/auth/user/': auth_controller.User
'/auth/provider/<provider>/': auth_controller.Provider
'/auth/callback/<provider>/': auth_controller.Callback
'/auth/cluster/': cluster_controller.ClusterList
'/auth/cluster/<cluster>/': cluster_controller.ClusterInstance
'/auth/cluster/<cluster>/machine/': machine_controller.Machine
