mysql:
  data-location: "/var/lib/mysql"
  backup: "mysqldump --user=<DATABASE_USER> --password=<DATABASE_PASSWORD> --all-databases > %TMP_DUMP_DIR%/backup.sql"
  restore: "exec(\"/usr/bin/mysql -u<DATABASE_USER> -p<DATABASE_PASSWORD> <DATABASE_NAME>\")"
  test: "ls /var/lib/mysql"
